# Site settings
title: TBOOX
motto: Welcome to the website for the TBOOX Open Source Project!
email: waruqi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the website for the TBOOX Open Source Project!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://tboox.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  waruqi

# Build settings
markdown: kramdown
