# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TBOOX
brief-intro: Welcome to the website for the TBOOX Open Source Project!
brief-intro-cn: 欢迎来到TBOOX开源工程!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tboox.org" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: waruqi
facebook_username: waruqi
github_username:  waruqi
email: waruqi@gmail.com
weibo_username: 
zhihu_username: waruqi
linkedIn_username: 
dribbble_username: 

# description footer
description_footer: Copyright (c) 2016 tboox.org

# comments
duoshuo_shortname: tboox
disqus_shortname: zh-tboox

# statistic analysis 
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
baidu_tongji_id: 162f1cd478898a0686b0b5d5115e2af2
google_analytics_id: 

# ads
#adsbygoogle_client: ca-pub-5219622969547045
#adsbygoogle_slot: 2494302416

# markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# gems
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']

# multiple-languages
languages:          ['en', 'cn']
language_default:   'en'

# paginate
paginate: 5

