# Site settings
title: TBOOX
email: waruqi@gmail.com
description: Welcome to the website for the TBOOX Open Source Project!
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tboox.org" # the base hostname & protocol for your site

twitter_username: waruqi
github_username: waruqi
permalink: /:year/:month/:day/:title/

# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: zh-tboox
disqus_url: "http://www.tboox.org"

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# multiple-languages
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']
languages:          ['en', 'cn']
language_default:   'en'
